accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('update_my_profile/', views.update_my_profile,
         name='update_my_profile'),
    path('change_my_password/', views.change_password,
         name='change_my_password'),
    path('register/', views.register, name='register'),
    path('update_user/<int:pk>/', views.update_user, name='update_user'),
    path('delete_user/<int:pk>/', views.delete_user, name='delete_user'),
    path('admin_change_password/<int:pk>/', views.admin_change_password,
         name='admin_change_password'),
    path('users/', views.list_user, name='list_user'),
]

insuranceProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('insurance/', include('insurance.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    user_image = models.ImageField(upload_to='profile_image',
                                   blank=True, null=True)
    is_admin = models.BooleanField(default=True)

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username', 'first_name', 'last_name',
                  'email', 'user_image', 'is_admin')

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs\
            .update({'class': 'form-control'})
        self.fields['first_name'].widget\
            .attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['user_image'].widget.attrs\
            .update({'class': 'form-control-file'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'class': 'form-control'})


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name',
                  'email', 'user_image',)
        exclude = ('password',)

    def clean_password(self):
        return ""

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs\
            .update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['user_image'].widget.attrs\
            .update({'class': 'form-control-file'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})


class CustomUserChangeAdminForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name',
                  'email', 'user_image', 'is_admin', )

    def clean_password(self):
        return ""

    def __init__(self, *args, **kwargs):
        super(CustomUserChangeAdminForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs\
            .update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['user_image'].widget.attrs\
            .update({'class': 'form-control-file'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})

accounts/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login,\
    update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm, AdminPasswordChangeForm
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string

from accounts.decorators import admin_required
from accounts.forms import CustomUserCreationForm, CustomUserChangeForm, CustomUserChangeAdminForm
from accounts.models import CustomUser


def logout_user(request):
    logout(request)
    form = CustomUserCreationForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'accounts/login.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('insurance:list-employee')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('insurance:list-employee')
            else:
                return render(request, 'accounts/login.html',
                              {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'accounts/login.html',
                          {'error_message': 'Invalid login or invalid password'})
    return render(request, 'accounts/login.html')


@login_required
@admin_required
def register(request):
    print(request.POST)
    if "cancel" in request.POST:
        return redirect('accounts:list_user')
    form = CustomUserCreationForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            if user is not None:
                return redirect('accounts:list_user')

        else:
            messages.error(request, 'Please correct the error below.')
    context = {
        "form": form,
    }
    return render(request, 'accounts/register.html', context)


@login_required
def update_my_profile(request):
    print(request.POST)
    if "cancel" in request.POST:
        return redirect('insurance:list-employee')
    user = get_object_or_404(CustomUser, pk=request.user.id)
    print(user.password)
    form = CustomUserChangeForm(request.POST or None, request.FILES or None, instance=user)
    form.fields['username'].widget.attrs['readonly'] = True
    # form.fields['is_admin'].widget.attrs['disabled'] = True
    # form.fields['is_admin'].widget.attrs['checked'] = True
    if request.method == 'POST':
        print(request.POST['username'])
        if form.is_valid():
            user.save()
            return redirect('insurance:list-employee')
        else:
            messages.error(request, 'Please correct the error below.')
    password_form = AdminPasswordChangeForm(request.user)
    return render(request, 'accounts/update_my_profile.html', {'form': form, 'password_form': password_form})


@login_required
@admin_required
def list_user(request):
    user_list = CustomUser.objects.all().exclude(id=request.user.id)
    form = AdminPasswordChangeForm(request.user)

    return render(request, 'accounts/user_list.html', {
        'users': user_list,
        'form': form
    })


@login_required
@admin_required
def update_user(request, pk):
    if "cancel" in request.POST:
        return redirect('accounts:list_user')

    user = get_object_or_404(CustomUser, pk=pk)
    form = CustomUserChangeAdminForm(request.POST or None, request.FILES or None,
                                     instance=user)
    if request.method == 'POST':
        if form.is_valid():
            user.save()
            return redirect('accounts:list_user')
        else:
            return render(request, 'accounts/register.html', {'form': form, })
    else:
        form = CustomUserChangeAdminForm(instance=user)
    return render(request, 'accounts/register.html', {'form': form, })


@login_required
@admin_required
def delete_user(request, pk):
    user = get_object_or_404(CustomUser, pk=pk)
    data = dict()

    if request.method == 'POST':
        user.delete()
        data['form_is_valid'] = True
        users = CustomUser.objects.all().exclude(id=request.user.id)
        data['html_user_list'] = render_to_string('accounts/partial_user_list.html', {
            'users': users
        })
    else:
        context = {'user': user, }
        data['html_form'] = render_to_string('accounts/partial_user_delete.html', context, request=request, )

    return JsonResponse(data)


@login_required
def change_password(request):
    if "cancel" in request.POST:
        return redirect('accounts:update_my_profile')
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:update_my_profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })


@login_required
@admin_required
def admin_change_password(request, pk):
    if "cancel" in request.POST:
        return redirect('accounts:list_user')
    user_change = get_object_or_404(CustomUser, pk=pk)
    if request.method == 'POST':
        form = AdminPasswordChangeForm(user_change, request.POST)
        if form.is_valid():
            messages.success(request, ' password was successfully updated!')
            return redirect('accounts:list_user')
        else:
            messages.error(request, 'Please correct the error below.')
            return redirect('accounts:list_user')
    else:
        form = AdminPasswordChangeForm(user_change)
    return render(request, 'accounts/change_password.html', {
        'form': form
    })

accounts/templates/accounts/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Insurance{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'image/logo2.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/all.min.css' %}"/>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>  <!-- JQUERY HERE -->
    <script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/bootstrap-toggle.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="{% static 'accounts/js/main.js' %}"></script>




</head>
<body>
<nav class="navbar navbar-expand-lg navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#" style="pointer-events: none; cursor: default;"><img  src="{% static 'image/logo2.png' %}" class="logo"></a>

        </div>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
 <ul class="navbar-nav mr-auto">
                <!--<li class="{% block register_active %}{% endblock %}"><a href="{% url 'accounts:register' %}">Register</a></li>-->
                <li class="nav-item {% block login_active %}{% endblock %}"><span class="fas fa-sign-in-alt"></span><a href="{% url 'accounts:login_user' %}">Log In</a></li>
            </ul>
</div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
<script>
$(".chosen").chosen()
</script>
</html>

accounts/templates/accounts/change_password.html
{% extends 'insurance/base.html' %}
{% block title %}Change Password{% endblock %}
<!--{% block users_active %}active{% endblock %}-->

{% block body %}
<div class="container-fluid">

    <div class="form-row">
        <div class="form-group col-md-12 ">

                    <h1>Change password</h1>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="row" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'insurance/change_password_admin.html' %}
                        <div class="form-group col-md-12">
                            <div class="row">
                            <div class="offset-3 col-md-3"><input formnovalidate  type="submit" name="cancel" value="Cancel" class="btn btn-secondary btn-lg"/></div>
                            <div class="offset-2 col-md-3"><button type="submit" class="btn btn-primary btn-lg"><span class="fas fa-check"></span>Save Password</button></div>


                            </div>
                        </div>
                    </form>

        </div>
    </div>

</div>

{% endblock %}

accounts/templates/accounts/form_template.html
{% for field in form %}

    <div class="col-md-6">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label" for="song_title">{{ field.label_tag }}</label>
        {{ field }}

    </div>
{% endfor %}

accounts/templates/accounts/login.html
{% extends 'accounts/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}
{% block body %}



  <div class="auth__header">
    <div class="auth__logo">
      <img src="/static/image/logo.png" alt="">
    </div>
  </div>
  <div class="auth__body">

    <form class="auth__form" role="form" action="{% url 'accounts:login_user'%}" method="post" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}
      <div class="auth__form_body">
        <h3 class="auth__form_title">Sign in</h3>
        <div>
          <div class="form-group">
            <label class="text-uppercase small">Username:</label>
            <input name="username" type="text" class="form-control" placeholder="Username" required>
          </div>
          <div class="form-group">
            <label class="text-uppercase small">Password</label>
            <input name="password" type="password" class="form-control" placeholder="Password" required>
          </div>
        </div>
      </div>
      <div class="auth__form_actions">
        <button type="submit" class="btn btn-primary btn-lg btn-block">
          LOGIN
        </button>

      </div>
    </form>
    {% if error_message %}
    <div class="alert alert-danger col-md-2 col-md-offset-5" role="alert">

                        <strong>{{ error_message }}</strong>

</div>
{% endif %}

  </div>

{% endblock %}

accounts/templates/accounts/partial_user_delete.html
<form method="post" action="{% url 'accounts:delete_user' user.id %}" class="js-user-delete-form">
  {% csrf_token %}
  <div class="modal-header">
  <h4 class="modal-title">Confirm User deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the User <strong>{{ user.username }} </strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

accounts/templates/accounts/partial_user_list.html
{% for user in users %}
   <tr>
       <td>{{ user.username }}</td>
       <td>{{ user.first_name }} {{ user.last_name }}</td>
       <td>
           {% if user.is_admin %}
           <strong style="color: blue ">{{ user.is_admin }}</strong>
           {% else %}
           {{ user.is_admin }}
           {% endif %}
       </td>
       <td>

          <a href="{% url 'accounts:update_user' user.id %}">
          <button  class="btn btn-warning btn-xs">
          <span class="far fa-edit"></span>&nbsp; Edit &nbsp;&nbsp;
          </button>
          </a>

          <button data-url="{% url 'accounts:admin_change_password' user.id %}"  class="btn btn-default btn-xs js-update-pw">
          <span class="fas fa-key"></span>&nbsp;Password &nbsp;&nbsp;
          </button>

           <button type="button"
             class="btn btn-danger btn-xs js-delete-user"
             data-url="{% url 'accounts:delete_user' user.id  %}">
             <span class="fas fa-trash-alt"></span> Delete
          </button>

           </td>
  </tr>
{% empty %}
  <tr>
     <td colspan="7" class="text-center bg-warning">No User</td>
  </tr>
 {% endfor %}




 <div class="modal fade" id="modal-change-password">
    <div class="modal-dialog">
      <div class="modal-content">
        <form method="post" action="" id="js-update-password">
          {% csrf_token %}
          <div class="modal-header">
          <h4 class="modal-title">Change Password</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            {% include 'accounts/form_template.html' %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="btnclose">Close</button>
            <button type="submit" class="btn btn-danger">Ok</button>
          </div>
        </form>
      </div>
    </div>
</div>

accounts/templates/accounts/register.html
{% extends 'insurance/base.html' %}
{% block title %}Register{% endblock %}
{% block users_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="form-group col-md-12">

                    <h1>Register for an Account</h1>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="row" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'accounts/form_template.html' %}
                        <div class="form-group col-md-12">
                            <div class="row">
                            <div class="col-md-6">
                            <input formnovalidate  type="submit" name="cancel" value="Cancel" class="btn btn-secondary btn-lg"/>
                            </div>
                            <div class="col-md-6">
                            <button type="submit" class="btn btn-primary btn-lg"><span class="fas fa-check"></span>Submit</button>
                            </div>



                            </div>
                        </div>
                    </form>

        </div>
    </div>

</div>

{% endblock %}

accounts/templates/accounts/update_my_profile.html
{% extends 'insurance/base.html' %}
{% block title %}My Profile{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="form-group col-md-12">

                <div class="card-title">
                <div class="top-text">

                <a href="{% url 'accounts:change_my_password' %}"  class="btn btn-default btn-xs">Change password maybe !?🤔🤔🤔</a>
                </div>

                    {% if user.is_admin %}
                    <h4>You Are Admin</h4>
                    {% endif %}
                </div>



                    <h1>Edit My Profile</h1>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="row" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'accounts/form_template.html' %}
                        <div class="form-group col-md-12">
                            <div class="row">
                            <div class="col-md-6"><input formnovalidate  type="submit" name="cancel" value="Cancel" class="btn btn-secondary btn-lg"/></div>
                            <div class="col-md-6"><button type="submit" class="btn btn-primary btn-lg"><span class="fas fa-edit"></span>Submit</button></div>


                            </div>
                        </div>
                    </form>


        </div>
    </div>

</div>



{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'insurance/base.html' %}
{% block title %}All Users{% endblock %}
{% block users_active %}active{% endblock %}

{% load static %}
{% block javascript %}
  <script src="{% static 'accounts/user.js' %}"></script>
{% endblock %}

{% block body %}

<div class="container-fluid songs-container">
    <div class="row">
        <div class="col-sm-12">
<div class="top-btn">
                <a href="{% url 'accounts:register' %}" >
                    <button class="btn btn-primary">
                        <span class="fas fa-plus" aria-hidden="true"></span>&nbsp;New User
                    </button>
                </a>

</div>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-8">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table" id="user-table">
                        <thead>
                            <tr>
                                <th scope="col">Username</th>
                                <th scope="col">Name</th>
                                <th scope="col">Is Admin</th>
                                <th scope="col">Actions</th>

                            </tr>
                        </thead>
                        <tbody>
                        {% include 'accounts/partial_user_list.html' %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

<div class="modal fade" id="modal-user">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
</div>

{% endblock %}