accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('update_my_profile/', views.update_my_profile,
         name='update_my_profile'),
    path('change_my_password/', views.change_password,
         name='change_my_password'),
    path('register/', views.register, name='register'),
    path('update_user/<int:pk>/', views.update_user, name='update_user'),
    path('delete_user/<int:pk>/', views.delete_user, name='delete_user'),
    path('admin_change_password/<int:pk>/', views.admin_change_password,
         name='admin_change_password'),
    path('users/', views.list_user, name='list_user'),
]

insurance/urls.py
from django.urls import path
from . import views

app_name = 'insurance'
urlpatterns = [
    # employee
    path('employee/add/', views.create_employee,
         name='create-employee'),
    path('employee/delete/<int:pk>/<int:page>/', views.delete_employee,
         name='delete-employee'),
    path('employee/update/<int:pk>/', views.update_employee,
         name='update-employee'),
    path('employees/', views.list_employee, name='list-employee'),
    # family
    path('employee/<int:pk>/', views.detail_employee,
         name='detail-employee'),
    path('employee/<int:pk>/add-family/', views.create_family,
         name='create-family'),
    path('employee/<int:pk>/update-family/<int:pk2>/', views.update_family,
         name='update-family'),
    path('employee/<int:pk>/delete-family/<int:pk2>/', views.delete_family,
         name='delete-family'),
    # relation
    path('list-relation/', views.list_relation, name='list-relation'),
    path('create-relation/', views.create_relation,
         name='create-relation'),
    path('create-status/', views.create_status, name="create_status"),
    path('update-status/<int:pk>/', views.update_status, name="update_status"),
    path('delete-status/<int:pk>/', views.delete_status, name="delete_status"),
    path('update-relation/<int:pk>/', views.update_relation,
         name='update-relation'),
    path('delete-relation/<int:pk>/', views.delete_relation,
         name='delete-relation'),

    path('create', views.create, name='create'),

    path('details/<int:pk>', views.detail, name='details'),

    path('', views.index,
         name='index'),
    path('delete/<int:pk>', views.delete,
         name='delete'),
    path('update/<int:pk>', views.update,
         name='update'),
    path('update-state/<int:pk>/<int:pk_status>/', views.updateState,
         name='update-state'),
    path('collaborator-patient/<int:pk>', views.collaboratorPatient,
         name='collaborator-patient'),
]

insuranceProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('insurance/', include('insurance.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insurance/forms.py
from django import forms


from insurance.models import Employee, Family, Relation, FileInsurance, Status, Person


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)

        self.fields['service_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control'})
        self.fields['address'].widget.attrs.update({'class': 'form-control'})
        self.fields['employee_image'].widget.attrs.update({'class': 'form-control-file'})
        self.fields['function'].widget.attrs.update({'class': 'form-control'})
        self.fields['hiring_date'].widget.attrs.update({'class': 'datepicker form-control', 'onkeydown': 'return false'})
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['birth_date'].widget.attrs.update({'class': 'datepicker form-control', 'onkeydown': 'return false'})
        self.fields['sex'].widget.attrs.update({'class': 'form-control'})


class FamilyForm(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['name', 'first_name', 'birth_date', 'sex', 'relation']

    def __init__(self, *args, **kwargs):
        super(FamilyForm, self).__init__(*args, **kwargs)

        self.fields['birth_date'].widget.attrs.update({'class': 'datepicker form-control', 'onkeydown': 'return false'})


class RelationForm(forms.ModelForm):
    class Meta:
        model = Relation
        fields = '__all__'


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = '__all__'


class FileInsuranceForm(forms.ModelForm):
    Patients = forms.ModelMultipleChoiceField(queryset=None)

    class Meta:
        model = FileInsurance
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(FileInsuranceForm, self).__init__(*args, **kwargs)
        self.fields['delivery_date'].widget.attrs.update({'class': 'datepicker form-control', 'onkeydown': 'return false', 'autocomplete': 'off'})
        self.fields['filing_date'].widget.attrs.update({'class': 'datepicker form-control', 'onkeydown': 'return false', 'autocomplete': 'off'})
        self.fields['Repayment_date'].widget.attrs.update({'class': 'datepicker form-control', 'onkeydown': 'return false', 'autocomplete': 'off'})
        self.fields['Patients'].queryset = Person.objects.all()
        self.fields['Patients'].widget.attrs.update({'class': 'form-control'})
        self.fields['Patient'].widget = forms.HiddenInput()
        self.fields['amount'].widget.attrs.update({'class': 'form-control'})
        self.fields['status'].widget.attrs.update({'class': 'form-control'})
        self.fields['file_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['amount_reimbursed'].widget.attrs.update({'class': 'form-control'})
        self.fields['collaborator'].widget.attrs.update({'class': 'chosen form-control'})
        self.fields['regulation_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['method_settlement'].widget.attrs.update({'class': 'form-control', 'id': 'checkMethod'})
        self.fields['check_number'].widget.attrs.update({'class': 'form-control', 'id': 'checkMethod2'})

insurance/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string

from accounts.decorators import admin_required
from insurance.forms import EmployeeForm, FamilyForm, RelationForm, FileInsuranceForm, StatusForm
from insurance.models import Employee, Family, Relation, FileInsurance, Status


@login_required
def detail_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    return render(request, 'insurance/detail_employee.html',
                  {'employee': employee, })


@login_required
def create_employee(request):
    form = EmployeeForm(request.POST or None, request.FILES or None)
    if "cancel" in request.POST:
        return redirect('insurance:list-employee')

    if form.is_valid():
        employee = form.save(commit=False)
        employee.save()
        return redirect('insurance:list-employee')
    return render(request, 'insurance/create_employee.html', {"form": form, })


@login_required
def update_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = EmployeeForm(request.POST or None, request.FILES or None,
                        instance=employee)
    if "cancel" in request.POST:
        return redirect('insurance:list-employee')

    if request.method == 'POST':
        if form.is_valid():
            employee.save()
            return redirect('insurance:list-employee')
    else:
        form = EmployeeForm(instance=employee)
    return render(request, 'insurance/update_employee.html', {'form': form, })


@login_required
def delete_employee(request, pk, page):
    employee = get_object_or_404(Employee, pk=pk)
    data = dict()
    if request.method == 'POST':
        employee.delete()
        employee_list = Employee.objects.all()

        paginator = Paginator(employee_list, 4)

        if (page - 1) == paginator.num_pages:
            page = paginator.num_pages
        page_current = request.GET.get('page', page)
        try:
            employees = paginator.page(page_current)
        except PageNotAnInteger:
            employees = paginator.page(page)
        except EmptyPage:
            employees = paginator.page(paginator.num_pages)
        employees.number = page
        data['form_is_valid'] = True  # This is just to play along with the existing code
        data['html_employee_list'] = render_to_string('insurance/partial_employee_list.html', {
            'employees': employees
        })
    else:
        context = {'employee': employee, 'page': page}
        data['html_form'] = render_to_string('insurance/partial_employee_delete.html',
                                             context,
                                             request=request,
                                             )
    return JsonResponse(data)


@login_required
def list_employee(request):
    employee_list = Employee.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(employee_list, 4)
    try:
        employees = paginator.page(page)
    except PageNotAnInteger:
        employees = paginator.page(1)
    except EmptyPage:
        employees = paginator.page(paginator.num_pages)
    return render(request, 'insurance/employees.html', {
        'employees': employees,
    })


def save_family_form(request, form, employee, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            family = form.save(commit=False)
            family.employee_relation = employee
            family.save()
            data['form_is_valid'] = True
            data['html_family_list'] = render_to_string('insurance/partial_family_list.html', {
                'employee': employee
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form, 'employee': employee}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@login_required
def create_family(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    if request.method == 'POST':
        form = FamilyForm(request.POST or None, request.FILES or None)
    else:
        form = FamilyForm()
    return save_family_form(request, form, employee, 'insurance/partial_family_create.html')


@login_required
def update_family(request, pk, pk2):
    employee = get_object_or_404(Employee, pk=pk)
    family = get_object_or_404(Family, pk=pk2)
    if request.method == 'POST':
        form = FamilyForm(request.POST or None, request.FILES or None, instance=family)
    else:
        form = FamilyForm(instance=family)
    return save_family_form(request, form, employee, 'insurance/partial_family_update.html')


@login_required
def delete_family(request, pk, pk2):
    employee = get_object_or_404(Employee, pk=pk)
    family = get_object_or_404(Family, pk=pk2)
    data = dict()
    if request.method == 'POST':
        family.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        data['html_family_list'] = render_to_string('insurance/partial_family_list.html', {
            'employee': employee
        })
    else:
        context = {'family': family, 'employee': employee}
        data['html_form'] = render_to_string('insurance/partial_family_delete.html', context, request=request, )
    return JsonResponse(data)


@login_required
@admin_required
def list_relation(request):
    relations = Relation.objects.all()
    all_status = Status.objects.all()
    return render(request, 'insurance/list_relation.html', {
        'relations': relations, "all_status": all_status
    })


def save_relation_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            relation = form.save(commit=False)
            relation.save()
            data['form_is_valid'] = True
            relations = Relation.objects.all()
            data['html_relation_list'] = render_to_string('insurance/partial_relation_list.html',
                                                          {'relations': relations})
        else:
            data['form_is_valid'] = False
    context = {'form': form, }
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def save_status_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            all_status = Status.objects.all()
            data['html_status_list'] = render_to_string('insurance/partial_status_list.html', {
                'all_status': all_status
            })
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form_status'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


@login_required
@admin_required
def create_relation(request):
    if request.method == 'POST':
        form = RelationForm(request.POST or None, request.FILES or None)
    else:
        form = RelationForm()
    return save_relation_form(request, form, 'insurance/partial_relation_create.html')


@login_required
@admin_required
def create_status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
    else:
        form = StatusForm()
    return save_status_form(request, form, 'insurance/create_status.html')


@login_required
@admin_required
def update_status(request, pk):
    status = get_object_or_404(Status, pk=pk)
    if request.method == 'POST':
        form = StatusForm(request.POST, instance=status)
    else:
        form = StatusForm(instance=status)
    return save_status_form(request, form, 'insurance/update_status.html')


@login_required
@admin_required
def delete_status(request, pk):
    status = get_object_or_404(Status, pk=pk)
    data = dict()
    if request.method == 'POST':
        status.delete()
        data['form_is_valid'] = True
        all_status = Status.objects.all()
        data['html_status_list'] = render_to_string('insurance/partial_status_list.html', {
            'all_status': all_status
        })
    else:
        context = {'status': status, }
        data['html_form_status'] = render_to_string('insurance/partial_status_delete.html', context, request=request, )
    return JsonResponse(data)


@login_required
@admin_required
def update_relation(request, pk):
    relation = get_object_or_404(Relation, pk=pk)
    if request.method == 'POST':
        form = RelationForm(request.POST or None, request.FILES or None, instance=relation)
    else:
        form = RelationForm(instance=relation)
    return save_relation_form(request, form, 'insurance/partial_relation_update.html')


@login_required
@admin_required
def delete_relation(request, pk):
    relation = get_object_or_404(Relation, pk=pk)
    data = dict()
    if request.method == 'POST':
        relation.delete()
        data['form_is_valid'] = True
        relations = Relation.objects.all()
        data['html_relation_list'] = render_to_string('insurance/partial_relation_list.html', {
            'relations': relations
        })
    else:
        context = {'relation': relation, }
        data['html_form'] = render_to_string('insurance/partial_relation_delete.html', context, request=request, )
    return JsonResponse(data)


@login_required
def create(request):
    if 'cancel' in request.POST:
        return redirect('insurance:index')

    insurance = FileInsuranceForm(request.POST or None)
    if insurance.is_valid():
        insurance.save()
        insurance.instance.Patient = insurance.cleaned_data['Patients'].first()
        insurance.instance.save()

        messages.info(request, 'insurance created successfully')

insurance/templates/insurance/create_fam.html
{% extends 'insurance/base.html' %}
{% block title %}Add a New Family{% endblock %}
{% block employees_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">



        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New  Family</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="employee" value="{{ employee }}">
                        {% include 'accounts/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

insurance/templates/insurance/form_insurance.html
{% extends 'insurance/base.html' %}
{% load staticfiles %}
{% block title %}Add a new insurance file {% endblock %}
{% block insurances_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">


            <div class="form-group col-md-12">

                        <img  src="{% static 'image/logo.png' %}" class="img-logo">


                    <h1>Add a New Insurance File</h1>
                    <form class="row" role="form" action="{% url 'insurance:create' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'insurance/create_file_insurance.html' %}
                        <div class="form-group col-md-12">

<div class="row">
                         <div class="col-md-6 col-xs-6">
                                 <input formnovalidate  type="submit" name="cancel" value="Cancel" class="btn btn-secondary btn-lg"/>
                            </div>
                            <div class="col-md-6 col-xs-6">

                                <button type="submit" class="btn btn-primary btn-lg"><span class="fas fa-check"></span>Submit</button>
                            </div>
                        </div>
                        </div>
                    </form>


            </div>





    </div>

</div>
{% endblock %}

insurance/templates/insurance/index_insurance.html
{% extends 'insurance/base.html' %}
{% block title %}Add a new insurance file {% endblock %}
{% block insurances_active %}active{% endblock %}

{% block body %}

<div class="container-fluid songs-container">
    <div class="row">
        <div class="col-sm-12">
<div class="top-btn">
                <a href="{% url 'insurance:create' %}" >
                    <button class="btn btn-primary">
                        <span class="fas fa-plus" aria-hidden="true"></span>&nbsp;New file insurance
                    </button>
                </a>
</div>

        </div>
    </div>

    <div class="row">

        <div class="col-md-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table" id="employee-table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Filing date</th>
                                <th>Amount</th>
                                <th>Delivery date</th>
                                <th>File Number</th>
                                <th>Repayment date</th>
                                <th>Amount reimbursed</th>
                                <th>Patient</th>
                                <th>Statut</th>

                                <th></th>
                                <th>Change Statut</th>

                            </tr>
                        </thead>
                        <tbody>
                        {% include 'insurance/insurance_list.html' %}
                        </tbody>
                    </table>
                    <!--{% if insurances.has_other_pages %}-->
                      <!--<ul class="pagination">-->
                        <!--{% if insurances.has_previous %}-->
                          <!--<li><a href="?page={{ insurances.previous_page_number }}">&laquo;</a></li>-->
                        <!--{% else %}-->
                          <!--<li class="disabled"><span>&laquo;</span></li>-->
                        <!--{% endif %}-->
                        <!--{% for i in insurances.paginator.page_range %}-->
                          <!--{% if insurances.number == i %}-->
                            <!--<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>-->
                          <!--{% else %}-->
                            <!--<li><a href="?page={{ i }}">{{ i }}</a></li>-->
                          <!--{% endif %}-->
                        <!--{% endfor %}-->
                        <!--{% if insurances.has_next %}-->
                          <!--<li><a href="?page={{ insurances.next_page_number }}">&raquo;</a></li>-->
                        <!--{% else %}-->
                          <!--<li class="disabled"><span>&raquo;</span></li>-->
                        <!--{% endif %}-->
                      <!--</ul>-->
                    <!--{% endif %}-->
                </div>
            </div>

        </div>

    </div>

</div>

<div class="modal fade" id="modal-employee">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
</div>

{% endblock %}

insurance/templates/insurance/partial_family_create.html
<form method="post" action="{% url 'insurance:create-family'  employee.id %}" class="js-family-create-form">
  {% csrf_token %}
  <div class="modal-header">

    <h4 class="modal-title">Create a new Family</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <input type="hidden" name="employee" value="{{ employee }}">
    {% include 'insurance/partial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create </button>
  </div>
</form>

insurance/templates/insurance/partial_family_delete.html
<form method="post" action="{% url 'insurance:delete-family' employee.id family.id %}" class="js-family-delete-form">
  {% csrf_token %}
  <div class="modal-header">
  <h4 class="modal-title">Confirm Family deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the family <strong>{{ family.name}} &nbsp;{{ family.first_name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

insurance/templates/insurance/partial_family_list.html
  {% for family in employee.family_set.all %}
  <tr>
      <td>{{ family.name}} {{ family.first_name }}</td>
      <td>{{ family.relation }}</td>
      <td>
      <!--<form action="{% url 'insurance:delete-family' employee.id family.id %}" method="post" style="display: inline;">-->
          <!--{% csrf_token %}-->
          <!--<input type="hidden" name="family_id" value="{{ family.id }}" />-->
          <!--<button type="submit" class="btn btn-danger btn-xs">-->
              <!--<span class="glyphicon glyphicon-remove"></span>&nbsp; Delete-->
          <!--</button>-->
      <!--</form>-->

          <button type="button"
              class="btn btn-warning btn-xs js-update-family"
              data-url="{% url 'insurance:update-family'  employee.id family.id %}">
            <span class="far fa-edit"></span> Edit &nbsp;&nbsp;
          </button>
          <button type="button"
              class="btn btn-danger btn-xs js-delete-family"
              data-url="{% url 'insurance:delete-family' employee.id family.id %}">
              <span class="fas fa-trash-alt"></span> Delete
          </button>
      </td>
  </tr>
  {% empty %}
       <tr>
           <td colspan="7" class="text-center bg-warning">No Family</td>
       </tr>
  {% endfor %}

insurance/templates/insurance/partial_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

insurance/templates/insurance/partial_relation_list.html
{% for relation in relations %}
   <tr>
       <td>{{ relation.parental_relation }}</td>
       <td>
           <button type="button"
              class="btn btn-warning btn-xs js-update-relation"
              data-url="{% url 'insurance:update-relation'  relation.id %}">
            <span class="far fa-edit"></span> Edit &nbsp;&nbsp;
          </button>

           <button type="button"
             class="btn btn-danger btn-xs js-delete-relation"
             data-url="{% url 'insurance:delete-relation' relation.id  %}">
             <span class="fas fa-trash-alt"></span> Delete
          </button>

           </td>
  </tr>
{% empty %}
  <tr>
     <td colspan="7" class="text-center bg-warning">No Ralation</td>
  </tr>
 {% endfor %}

insurance/templates/insurance/partial_relation_update.html
<form method="post" action="{% url 'insurance:update-relation' form.instance.pk %}" class="js-relation-update-form">
  {% csrf_token %}
  <div class="modal-header">
  <h4 class="modal-title">Update relation</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

  </div>
  <div class="modal-body">
    {% include 'insurance/partial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update relation</button>
  </div>
</form>

insurance/templates/insurance/partial_status_delete.html
<form method="post" action="{% url 'insurance:delete_status' status.id %}" class="js-status-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">Confirm status deletion</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete this status <strong>{{ status.status }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete status</button>
  </div>
</form>

insurance/templates/insurance/partial_status_list.html
{% for status in all_status %}
   <tr>
       <td>{{ status.status }}</td>
       <td>
           <button type="button"
              class="btn btn-warning btn-xs js-update-status"
              data-url="{% url 'insurance:update_status'  status.id %}">
            <span class="far fa-edit"></span> Edit &nbsp;&nbsp;
          </button>

           <button type="button"
             class="btn btn-danger btn-xs js-delete-status"
             data-url="{% url 'insurance:delete_status' status.id  %}">
             <span class="fas fa-trash-alt"></span> Delete
          </button>

           </td>
  </tr>
{% empty %}
  <tr>
     <td colspan="7" class="text-center bg-warning">No Status</td>
  </tr>
 {% endfor %}

insurance/templates/insurance/update_employee.html
{% extends 'insurance/base.html' %}
{% block title %}Update Employee{% endblock %}
{% block employees_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="form-group col-md-12">

                    <h1>Update a Employee</h1>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="row" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'accounts/form_template.html' %}
                        <div class="form-group col-md-12">
                            <div class="row">
                                    <div class="col-md-6 col-xs-6">

                                               <input formnovalidate  type="submit" name="cancel" value="Cancel" class="btn btn-secondary btn-lg"/>
                                    </div>
                                    <div class="col-md-6 col-xs-6">
                                            <button type="submit" class="btn btn-primary btn-lg"><span class="fas fa-undo-alt"></span>Update</button>

                                    </div>
                            </div>
                        </div>
                    </form>

        </div>

    </div>

</div>
{% endblock %}

insurance/templates/insurance/update_status.html
<form method="post" action="{% url 'insurance:update_status' form.instance.pk%}" class="js-status-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <h4 class="modal-title">update status</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'insurance/partial_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">update status</button>
  </div>
</form>